[package]
name = "a-bad-stack"
version = "0.1.0"
authors = ["Pawe≈Ç Przeniczny <pawel.przeniczny@airhelp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
